# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JChat
  pod 'JMessage'
  pod 'JPush'
  pod 'SVProgressHUD'
  pod 'SnapKit'
  pod 'Sugar'
  pod 'IQKeyboardManagerSwift'
  pod 'TZImagePickerController'
  pod 'SKPhotoBrowser'
  
end
